services:
  ollama:
    image: ollama/ollama:latest
    container_name: tranquil-inbox-ward-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - pmail
    restart: always
    # 开启 vulkan
    environment:
      - OLLAMA_VULKAN=1
    devices:
      - /dev/dri:/dev/dri
      # - /dev/kfd:/dev/kfd # AMD 独显
    # 开启 GPU 支持
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all  # 所有GPU
    #           capabilities: [gpu]

  app:
    build: .
    container_name: tranquil-inbox-ward-app
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=mollysama/rwkv-7-g1b:1.5b
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8501
      - SERVER_TIMEOUT=60
    depends_on:
      ollama:
        condition: service_started
    networks:
      - pmail
    restart: always

volumes:
  ollama_data:

networks:
  pmail:
    driver: bridge
    name: pmail
    external: true
